language: c
env:
  - TZ=America/New_York
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('pass') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppass
  - sudo service mysql restart
before_script:
  - echo $TZ | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql -u root -ppass -e 'CREATE DATABASE test;'
  - mysql -u root -ppass test < tests/integration/db/daemons.sql
  - mysql -u root -ppass test < tests/integration/db/meters.sql
  - mysql -u root -ppass test < tests/integration/db/meter_data.sql
  - mysql -u root -ppass test < tests/integration/db/api.sql
  - mysql -u root -ppass test < tests/integration/db/orgs.sql
  - sudo touch /root/meter_data.csv
  - sed -ie 's/time(NULL)/1577854800/g' buildingosd.c # set time to 2020-1-1 00:00:00
  - sed -ie 's|api.buildingos.com/o/token/|environmentaldashboard.org/dummy-bos-token|g' buildingosd.c
  - sed -ie "s/AND (id IN (SELECT meter_id FROM saved_chart_meters) OR id IN (SELECT meter_id FROM gauges) OR bos_uuid IN (SELECT elec_uuid FROM orbs) OR bos_uuid IN (SELECT water_uuid FROM orbs) OR bos_uuid IN (SELECT meter_uuid FROM relative_values WHERE permission = 'orb_server' AND meter_uuid != '')) AND id NOT IN (SELECT updating_meter FROM daemons WHERE target_res = 'live')//g" buildingosd.c # these extra conditions arent necessary to check
  - printf '#define DB_SERVER "localhost"\n#define DB_USER "root"\n#define DB_PASS "pass"\n#define DB_NAME "test"\n' > ./db.h
script:
  - make all
  - sudo ./buildingosd -o || true # need sudo for these so it can write to /root/meter_data.csv
  - sudo ./buildingosd -o || true
  - sudo ./buildingosd -o || true
  - sudo ./buildingosd -o -rquarterhour || true
  - sudo ./buildingosd -o -rhour || true
  - sudo wc -l /root/meter_data.csv
  - sudo cmp /root/meter_data.csv tests/integration/expected_data.csv
  - sudo cat /root/meter_data.csv
notifications:
  slack:
    rooms:
      - envdash:2Ml8eUe6ZTTOGDCcIHtjDaRb#devops
